trigger:
    - main
pr:
    - feature/*
    - fix/*
    - hostfix/*
    - main

pool:
    vmImage: ubuntu-latest

steps:
    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Run build'

    - task: ArchiveFiles@2
      inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

    - task: PublishBuildArtifacts@1
      inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
