const routes = {
  home: '/',
  signUp: '/sign-up',
  signIn: '/sign-in',
  displayCoin: '/display-coin',
  p2p: '/p2p',
  discover: '/discover',
  tokenDetailL: '/discover/detail/:symbol',
  homeDashboard: '/home-dashboard',
  reportOverview: '/report-overview',
  report: 'report',
  analyze: '/analyze',
  editProfile: '/edit-profile',
  changePassword: '/change-password',
  profile: '/profile',
  buyToken: '/upgrade',
  swapToken: '/swap-token',
  transactionShark: '/transaction-shark',
  gainLoss: '/gain-loss',
  portfolioSharkFollow: '/portfolio-shark-follow',
  blog: '/blog',
  blogDetail: '/blog/detail/:blogId',
};

export default routes;
